
CREATE TABLE torrents (
	id BIGSERIAL PRIMARY KEY NOT NULL
	,infohash BYTEA UNIQUE NOT NULL
	,seeds SMALLINT DEFAULT 0 NOT NULL
	,leeches SMALLINT DEFAULT 0 NOT NULL
	,last_scrape TIMESTAMP DEFAULT NOW() NOT NULL
);
